### PR TITLE
[FEATURE] Bluecode payment method

### PR DESCRIPTION
**Pull request by thommyhh**

### CODE REVIEW

**Comment by thommyhh** [comment]
@judgej Any chance, you can take a look at this?

**Comment by judgej** [comment]
Looks great. I haven't tried it, but it doesn't break any existing tests, and is a narrow enough scope to see what's going on.

If there are a few lines that would be useful in the dcumentation to highlight the feature, perhaps if there are any estrictions that need to be known (for example if Bluecode is only available to certain countries), then please feel free to add that, but I'm merging anyway.

Sorry this has taken so long to look at - this year I have been the busiest I've been in a long time.

Let me know if the merge works, and I'll tag it for release. Feels like a debug release in risk, but a minor version update is probably more warranted for the additional features.

**Comment by thommyhh** [comment]
@judgej I've added a section about Bluecode to the README. I will test the master and then will get back to you.
I think, as it is a new feature, we should tag a `3.1.0`.

**Comment by thommyhh** [comment]
@judgej The current master has been successfully tested. Will you create a 3.1.0 release or should I do that?

**Pull request merged**
